### ISSUE TITLE
[INFO] planned vendor API changes

### ISSUE THREAD

**Issue by philippdormann** [philippdormann/infoportal-api#1]
Ich konnte Kontakt mit dem direkten Entwickler der Web APIs herstellen.
Die APIs unter `/schule_portal/webservices/` sollen planmäßig zu "Ende des Jahres?" abgestellt werden, "hoffentlich haben bis dahin alle die Umstellung geschafft".
Die neuen APIs laufen über JSON-RPC (v1: PHPSESSION, v2: http basic auth), REST-APIs/ OpenAPI Definitionen gibt es leider nicht.
Dokumentation zu v1 / v2 APIs liegen mir vor.

---

I was able to contact the direct developer of the Web APIs.
The APIs under `/schule_portal/webservices/` are scheduled to be turned of at the "end of the year?", "hopefully everyone will have made the switch by then".
The new APIs run via JSON-RPC (v1: PHPSESSION, v2: http basic auth), unfortunately there are no REST-APIs/ OpenAPI definitions.
I have documentation on v1 / v2 APIs.

**Comment by philippdormann** [comment]
info
---
Sprechstunden kommen jetzt anscheinend schon nicht mehr über die Lehrer API zurück

**Comment by philippdormann** [comment]
## ❗ official deprecation date:
**31.12.2020**

**Comment by w00000dy** [comment]
Gibt es schon was neues zur JSON-RPC API?

**Comment by philippdormann** [comment]
Hi @WoodyLetsCode 😁

Die JSON-RPC APIs funktionieren ganz gut, habe ich in meinen live Projekten im produktiven Einsatz.

So wie es aussieht geben auch die aktuellen APIs immer noch Lehrer-Daten zurück.
Daa Ende der sunsetting phase ist immernoch der 31.12.20, Mal schauen :)

Kann ich dir konkret weiterhelfen?
Brauchst du die API Docs? Kann ich dir zukommen lassen 👀

**Comment by w00000dy** [comment]
Danke für die schnelle Antwort! 😁
Mit der API Dokumentation würdest du mir sehr weiterhelfen. Wo hast du die eigentlich her? Hab nichts dazu gefunden. 🤔

**Comment by philippdormann** [comment]
Gerne!
Ich lasse dir die API Docs inkl. Code Sample heute Nachmittag/ früher Abend zukommen 😉

Die Docs habe ich (s.o) aus dem direkten Austausch mit den Entwicklern von ABCSoft + meinem Vertragspartner (ehemalige Schule) 😀

**Comment by philippdormann** [comment]
Hey @WoodyLetsCode here you go 🙂
Wenn du Fragen hast meld' dich gerne 👍

## API Docs vom Hersteller

[infoportal_api_doc-v1.pdf](https://github.com/philippd1/infoportal-api/files/5666879/infoportal_api_doc-v1.pdf)
[infoportal_api_doc-v2.pdf](https://github.com/philippd1/infoportal-api/files/5666880/infoportal_api_doc-v2.pdf)

## sample code
```
<?php
/**
 * Beispiel Skript zur Verwendung der Funktion get_school_dates.
 *
 * Dieses Beispiel verwendet eine externe JSON-RPC Bibliothek.  Am einfachsten ist es
 * diese mit composer zu installien:
 *     composer require fguillot/json-rpc @stable
 * Alternativ kann man sie unter https://github.com/matasarei/JsonRPC herunter laden.
 * Es ist möglich die API auch mit einer beliebigen anderen Bibliothek zu verwenden,
 * der Code ist dann jedoch eventuell anzupassen.
 *
 * Zu Beginn der Datei finden sich drei Einstellungen die vor der Verwendung
 * angepasst werden müssen:
 * 1. der Pfad unter dem die JSON-RPC Bibliothek installiert wurde
 * 2. das Kürzel der Schule
 * 3. das Passwort für die API (muss im Infoportal gesetzt werden)
 *
 * Das Skript baut eine Verbindung zur API auf und ruft die allgemeinen Termine der
 * Schule ab.  Diese werden in einer HTML Tabelle dargestellt.  Es wird kein HTML
 * Header oder Footer mit ausgegeben, sodass dieses Skript direkt in eine bestehende
 * Seite eingebaut werden kann.
 */

/**
 * ACHTUNG: Die nächsten drei Zeilen müssen vor der Verwendung angepasst werden!
 */
require_once __DIR__.'/../vendor/autoload.php';
$school = 'schulkuerzel';
$password = 'passwort';

// Initialisierung der Verbindung zur API inklusive Login und Fehlermeldung.
$api_url = 'https://schule-infoportal.de/api/?version=2';
$api = new JsonRPC\Client($api_url);
$api->getHttpClient()
    ->withUsername($school)
    ->withPassword($password);

// Abholen der Daten aus der API.
$dates = $api->execute('get_school_dates', []);
```

**Comment by w00000dy** [comment]
Danke! 😃

**Comment by w00000dy** [comment]
Also benötige ich bei der neuen API immer ein Login-Passwort?
Bei der alten XML-RPC API ging es ja noch ohne Login-Daten.

**Comment by philippdormann** [comment]
@WoodyLetsCode ja. Wie in den docs beschrieben.
Die credentials kann der Admin im UI festlegen.
⏬
> Die neuen APIs laufen über JSON-RPC (v1: **PHPSESSION**, v2: **http basic auth**)

**Comment by w00000dy** [comment]
Okay! 😄  Danke für deine Hilfe!

**Comment by philippdormann** [comment]
Die API scheint mittlerweile defekt/ "ge-sunnsetted" zu sein. ☀
Vielleicht gibt es mal einen rewrite mit der neuen API 🤷‍♂️
